name: push
description: push
inputs:
- label: branch name
  type: text
  default: main
  name: branch
  required: 'true'
supported-os:
- windows
- linux
- mac
requirements-check:
  dependency-example:
    check-command: git --version
    info: git is not installed
command: git push -u origin "{{inputs.branch}}"

